# Generated by Django 5.0 on 2024-03-09 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='time'),
            preserve_default=False,
        ),
    ]
