# Generated by Django 5.0 on 2024-03-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
    ]
