# Generated by Django 5.0 on 2024-03-11 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_chat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountphoto',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time'),
            preserve_default=False,
        ),
    ]
