# Generated by Django 5.0 on 2024-03-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_accountphoto_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountphoto',
            name='created_date',
        ),
    ]
