# Generated by Django 5.0 on 2024-03-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_accountphoto_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountphoto',
            old_name='image',
            new_name='photo',
        ),
    ]
