# Generated by Django 5.0 on 2024-03-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=75, verbose_name='Article Title'),
        ),
    ]
