# Generated by Django 5.0 on 2024-03-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_article_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Like'),
        ),
    ]
