# Generated by Django 5.0 on 2024-03-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_advertisement_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
