# Generated by Django 5.0 on 2024-03-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_advertisement_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
