# Generated by Django 5.0 on 2024-04-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_share',
            field=models.BooleanField(default=False, verbose_name='Is share'),
        ),
        migrations.AddField(
            model_name='saved',
            name='is_share',
            field=models.BooleanField(default=False, verbose_name='Is share'),
        ),
    ]
