# Generated by Django 5.0 on 2024-05-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_groupmember_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_share',
            field=models.BooleanField(default=False, verbose_name='Is share'),
        ),
    ]
