# Generated by Django 5.0 on 2024-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_saved_image_saved_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='image',
            field=models.CharField(default='', max_length=500, verbose_name='image'),
        ),
    ]
