# Generated by Django 5.0 on 2024-05-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_saved_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.CharField(default='', max_length=500, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='message',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
