# Generated by Django 5.0 on 2024-05-10 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_channel_channelcontent_channelcontentcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelcontent',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
    ]
