# Generated by Django 5.0 on 2024-05-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_channelcontent_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='message_photo', verbose_name='photo'),
        ),
    ]
