# Generated by Django 5.0 on 2024-05-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_message_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='saved_message', verbose_name='photo'),
        ),
    ]
