# Generated by Django 5.0 on 2024-05-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_alter_saved_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_message_photo', verbose_name='photo'),
        ),
    ]
