# Generated by Django 5.0 on 2024-05-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_groupmessage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Message'),
        ),
    ]
